// swift-tools-version:5.3
// Generated by bin/generate_package.sh. Do not edit by hand.

import PackageDescription

let package = Package(
	name: "libgit2",
	platforms: [.iOS(.v13), .macOS(.v10_15)],
	products: [
		.library(
			name: "libgit2",
			targets: [
				"libgit2",
				"libssh2",
				"libssl",
				"libcrypto"
			]
		),
	],
	dependencies: [],
	targets: [
		.binaryTarget(
			name: "libgit2",
			url: "https://github.com/amine2233/spm-libgit2/releases/download/1.9.7/libgit2.zip",
			checksum: "ef9c097879987f385da31d4eb531f1a4707251fee0745ec30f457ddd2b9c279e"
		),
		.binaryTarget(
			name: "libssh2",
			url: "https://github.com/amine2233/spm-libgit2/releases/download/1.9.7/libssh2.zip",
			checksum: "386fd9b13dd665f7eee5f4c27e17fffad3fb1ef959900efa244d9f523029224e"
		),
		.binaryTarget(
			name: "libssl",
			url: "https://github.com/amine2233/spm-libgit2/releases/download/1.9.7/libssl.zip",
			checksum: "be0331cd4f913012d284f5a2d6eb52e93fe515aa78434da30a890a8fc68b79b9"
		),
		.binaryTarget(
			name: "libcrypto",
			url: "https://github.com/amine2233/spm-libgit2/releases/download/1.9.7/libcrypto.zip",
			checksum: "e0dff6d8228f2e02e0e4f5c599029646b776c3a088f411871218954c893590b2"
		),
	]
)
