my %targets = (
    "openssl-ios64" => {
        inherit_from => [ "ios64-xcrun" ],
    },
    "openssl-iossimulator-x86_64" => {
        inherit_from => [ "iossimulator-x86_64-xcrun" ],
    },
    "openssl-iossimulator-arm64" => {
        inherit_from => [ "iossimulator-arm64-xcrun" ],
    },
    "openssl-catalyst-x86_64" => {
        inherit_from => [ "darwin64-x86_64-cc" ],
        cflags => add("-target x86_64-apple-ios13.1-macabi"),
    },
    "openssl-catalyst-arm64" => {
        inherit_from => [ "darwin64-arm64-cc" ],
        cflags => add("-target arm64-apple-ios13.1-macabi"),
    },
    "openssl-mac64" => {
        inherit_from => [ "darwin64-x86_64-cc" ],
    },
    "openssl-macarm64" => {
        inherit_from => [ "darwin64-arm64-cc" ],
    },
)
