my %targets = (
    "openssl-ios64" => {
        inherit_from => [ "ios64-xcrun" ],
    },
    "openssl-iossimulator" => {
        inherit_from => [ "iossimulator-xcrun" ],
        cflags => add("-arch x86_64"),
    },
    "openssl-catalyst" => {
        inherit_from => [ "darwin64-x86_64-cc" ],
        cflags => add("-target x86_64-apple-ios-macabi"),
    },
    "openssl-mac64" => {
        inherit_from => [ "darwin64-x86_64-cc" ],
    },
    "openssl-macarm64" => {
        inherit_from => [ "darwin64-arm64-cc" ],
    },
)
